### ISSUE TITLE
[Bug Report] AutoButton Custom List Items Showing As "Unknown"

### ISSUE THREAD

**Issue by nhtwolf** [Merathilis/ElvUI_MerathilisUI#101]
### What is the issue you are having?

Adding custom items seems to work as they show on the bars correctly as does deleting but when trying to view the list they all show as "Unknown"

Full screenshot as requested in troubleshooting steps
![WoWScrnShot_101224_130351](https://github.com/user-attachments/assets/cde1ee74-b013-4e5d-96f2-96aac7e7a4d2)

### What is the expected behavior?

The item icon/name should be shown so you know what items are actually added, for instance WindTools has a similar module:
![image](https://github.com/user-attachments/assets/5faaa671-c589-493e-b41b-afb0c170b184)

### What actually happened?

Item list is showing all items as unknown.
![image](https://github.com/user-attachments/assets/9e4464a0-512f-4ad6-ad79-8eab772196b4)

I tested with only ElvUI & Merathalis to verify there wasn't a conflict and the items still shown as unknown.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/Merathilis/ElvUI_MerathilisUI/blob/development/CHANGELOG.md) and done the [Troubleshooting Steps](https://github.com/Merathilis/ElvUI_MerathilisUI/wiki/Troubleshooting).
- [X] I have disabled all addons except the AddOns called 'ElvUI' and 'ElvUI OptionsUI' and 'ElvUI_MerathilisUI' by using `/muidebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and/or MerathilisUI and another addon, make sure you include that information.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I gave you information above on which XPack i play Classic, WotLK or Retail.

**Comment by Merathilis** [comment]
Could you do me a favour, please download my dev. version and see if its fixed for you. If not feel free to reopen this ticket.

**Comment by nhtwolf** [comment]
Confirmed it works in the Dev version. Thank you so much!
![image](https://github.com/user-attachments/assets/c5f55e20-1cc6-43c2-9b98-63df473b4c11)
