### ISSUE TITLE
[Bug Report] Retail: OmniCD LUA error

### ISSUE THREAD

**Issue by nhtwolf** [Merathilis/ElvUI_MerathilisUI#103]
### What is the issue you are having?

The most recent update to OmniCD v2.8.9 is now causing errors with Merathilis

### What is the expected behavior?

No errors

### What actually happened?

LUA errors

### Suggested Solution/Workaround

It looks like OmniCD has changed to used Mixins now. I'm not familiar enough with how mixins work to know how to hook into them but hopefully this helps

![image](https://github.com/user-attachments/assets/30434ea5-e7c5-4dda-bd6e-715988569efe)

### Errors

```shell
1x ...s/ElvUI_MerathilisUI/Modules/Skins/Extern/OmniCD.lua:24: hooksecurefunc(): SetBorder is not a function
[string "=[C]"]: ?
[string "@ElvUI_MerathilisUI/Modules/Skins/Extern/OmniCD.lua"]:24: in function `OmniCD_Party_Icon'
[string "@ElvUI_MerathilisUI/Modules/Skins/Extern/OmniCD.lua"]:72: in function <...s/ElvUI_MerathilisUI/Modules/Skins/Extern/OmniCD.lua:66>
[string "=[C]"]: in function `xpcall'
[string "@ElvUI_MerathilisUI/Modules/Skins/Core.lua"]:129: in function `CallLoadedAddon'
[string "@ElvUI_MerathilisUI/Modules/Skins/Core.lua"]:208: in function <...aceElvUI_MerathilisUI/Modules/Skins/Core.lua:195>
[string "=[C]"]: ?
[string "@ElvUI_MerathilisUI/Core/Core.lua"]:111: in function `InitializeModules'
[string "@ElvUI_MerathilisUI/Init.lua"]:229: in function `?'
[string "@ElvUI_Libraries/Core/LibElvUIPlugin-1.0-46/LibElvUIPlugin-1.0.lua"]:309: in function <...aries/Core/LibElvUIPlugin-1.0/LibElvUIPlugin-1.0.lua:305>
[string "=[C]"]: in function `Initialize'
[string "@ElvUI/Core/init.lua"]:302: in function <ElvUI/Core/init.lua:301>
[string "=[C]"]: ?
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...aceMasque/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...aceMasque/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:
```

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/Merathilis/ElvUI_MerathilisUI/blob/development/CHANGELOG.md) and done the [Troubleshooting Steps](https://github.com/Merathilis/ElvUI_MerathilisUI/wiki/Troubleshooting).
- [X] I have disabled all addons except the AddOns called 'ElvUI' and 'ElvUI OptionsUI' and 'ElvUI_MerathilisUI' by using `/muidebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and/or MerathilisUI and another addon, make sure you include that information.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I gave you information above on which XPack i play Classic, WotLK or Retail.

**Comment by fang2hou** [comment]
@Merathilis 
I fixed the skin in WT.
https://github.com/wind-addons/ElvUI_WindTools/commit/2c4dd77124772e337fabbf286649655d569a1b6d
