### ISSUE TITLE
[Bug Report] Stone Soup

### ISSUE THREAD

**Issue by Calen81** [Merathilis/ElvUI_MerathilisUI#15]
### What is the issue you are having?

As soon as people puts down the new Raid Feast, Stone Soup, I get this error

### What is the expected behavior?

Not giving me an error?

### What actually happened?

.

### Errors

```shell
31x ...ilisUI\Mainline\Modules\Skins\FrameXML\UIWidgets.lua:37: Attempt to access forbidden object from code tainted by an AddOn
[string "=[C]"]: in function `SetAlpha'
[string "@ElvUI_MerathilisUI\Mainline\Modules\Skins\FrameXML\UIWidgets.lua"]:37: in function <...ilisUI\Mainline\Modules\Skins\FrameXML\UIWidgets.lua:34>
[string "@ElvUI_MerathilisUI\Mainline\Modules\Skins\FrameXML\UIWidgets.lua"]:145: in function <...ilisUI\Mainline\Modules\Skins\FrameXML\UIWidgets.lua:144>
[string "=[C]"]: in function `Setup'
[string "@Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua"]:459: in function `ProcessWidget'
[string "@Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua"]:495: in function `ProcessAllWidgets'
[string "@Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua"]:227: in function `RegisterForWidgetSet'
[string "@FrameXML\CompactUnitFrame.lua"]:1131: in function `CompactUnitFrame_UpdateWidgetSet'
[string "@FrameXML\CompactUnitFrame.lua"]:329: in function `CompactUnitFrame_UpdateAll'
[string "@FrameXML\CompactUnitFrame.lua"]:182: in function `CompactUnitFrame_SetUnit'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:417: in function `OnAdded'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:118: in function `OnNamePlateAdded'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:56: in function <...eBlizzard_NamePlates\Blizzard_NamePlates.lua:47>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = 0
```

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/Merathilis/ElvUI_MerathilisUI/blob/development/CHANGELOG.md) and done the [Troubleshooting Steps](https://github.com/Merathilis/ElvUI_MerathilisUI/wiki/Troubleshooting).

**Comment by Calen81** [comment]
I'll have to do that tonight as I'm about to go for work in an hour :)
As for the version; I'm using v. 4.90, which I believe is the current version? I always look for updates before each raid night, and this bug was happening Monday night during raid.
I do believe it's the actual nameplate/progress bar above the Stone Soup which is giving me the above error.

**Comment by Merathilis** [comment]
> I'll have to do that tonight as I'm about to go for work in an hour :) As for the version; I'm using v. 4.90, which I believe is the current version? I always look for updates before each raid night, and this bug was happening Monday night during raid. I do believe it's the actual nameplate/progress bar above the Stone Soup which is giving me the above error.

The error you are getting mention line 37 on my UIWidget.lua file... there are no line 37 in this file :>

**Comment by Merathilis** [comment]
Try now version 4.92

**Comment by Merathilis** [comment]
A fix for this should be now in ElvUI itself.

**Comment by Calen81** [comment]
Hey, sorry for the (really) late reply.
At first, I found out that BugGrabber/BugSack was some part of the problem. As soon as I disabled them, the error stopped coming.. Weird, right?

I just tested it now, with the update from ElvUI and Merathilis, and with BugGrabber/BugSack enabled, and no error has yet to occur.
