### ISSUE TITLE
Ugly borders appear with the new features.

### ISSUE THREAD

**Issue by reyard** [Merathilis/ElvUI_MerathilisUI#24]
### What is the issue you are having?

When I'm installing the 4.98 version at last update, borders appear in my weak auras. In 4.97 it is fine. I try disabling new features, but it is the same problem. In my next print screen I put borders in magenta color for check.

### What is the expected behavior?

It should be https://prnt.sc/ZovDW_lCkbuu

### What actually happened?

It is happened https://prnt.sc/zEI0le-QNtEz

### Suggested Solution/Workaround

The new features are beautiful, but I can't with this problem.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/Merathilis/ElvUI_MerathilisUI/blob/development/CHANGELOG.md) and done the [Troubleshooting Steps](https://github.com/Merathilis/ElvUI_MerathilisUI/wiki/Troubleshooting).

**Comment by Merathilis** [comment]
In your screenshot you have 500 other AddOns enabled, which makes it hard to tell if it is my AddOn or not. I only add a shadow border around WeakAura.

Please do the troubleshooting steps mentioned above and enable then also only WeakAura to test. For any further questions, please join my discord.

**Comment by reyard** [comment]
Ok now check this:
https://prnt.sc/M3uyNaVbjaG2
- All addons disabled
- Enabled Weak Auras with 1 aura (exclamation Icon)
- Enabled Elvui
- Enabled MerathilisUI


ElvUI_MerathilisUI-4.991 (Last Version)
https://prnt.sc/9edxfLlfKBvQ 
Can you see the square border around the exclamation icon?

Now It is ElvUI_MerathilisUI-4.97 (old version)
https://prnt.sc/i2-hOD1jb_7W
No border, It's clean.

**Comment by Merathilis** [comment]
What does the Widgets have to do with that? Its the WeakAura Skin, not the Widgets. If you dont want it, just disable it in my option.

Also look at your chat, actionbars.. etc. you have on every element this ugly border

**Comment by reyard** [comment]
It is disabled.
Idk why in the old version that square border is transparent or something
but in the new version in the weak auras icon and timers bar appear,
texture auras, models and text are fine.

**Comment by Merathilis** [comment]
Please, if you need further help join my discord. I will not anwer here anymore
