### ISSUE TITLE
[Bug Report] Certain Shaman buff reminders not working.

### ISSUE THREAD

**Issue by AphelionZero** [Merathilis/ElvUI_MerathilisUI#30]
### What is the issue you are having?

Lightning Shield and Flametongue weapon reminders are not showing when buff ends.

### What is the expected behavior?

I should see an icon to remind me to reapply the buff.

### What actually happened?

The buff reminder didn't show.

### Suggested Solution/Workaround

I looked at the .lua file but couldn't determine why it wasn't working as intended. 

### Errors

```shell
There are no errors.
```

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/Merathilis/ElvUI_MerathilisUI/blob/development/CHANGELOG.md) and done the [Troubleshooting Steps](https://github.com/Merathilis/ElvUI_MerathilisUI/wiki/Troubleshooting).

**Comment by Merathilis** [comment]
Works fine on my end tho. Please type in chat: `/muidebug on` after that type in chat: `/estatus` and post a whole UI Screenshot plx

**Comment by AphelionZero** [comment]
![WoWScrnShot_080822_142039](https://user-images.githubusercontent.com/44631598/183516929-1f0e60d8-a41e-40f3-8d1c-c7c6b441bc7e.jpg)

**Comment by Merathilis** [comment]
Do you have the Player UnitFrame disabled?

**Comment by AphelionZero** [comment]
I do, is that the issue?

**Comment by Merathilis** [comment]
Yes, because the Reminder is positioned on the Player Frame, if you disable it, it will not be shown :D

**Comment by Merathilis** [comment]
I will add an fallback, hold up

**Comment by Merathilis** [comment]
https://github.com/Merathilis/ElvUI_MerathilisUI/issues/30

Please download my dev. version and test it.

**Comment by AphelionZero** [comment]
Thank you very much! I'll test it as soon as the servers come back up.

**Comment by Merathilis** [comment]
Since you dont reported back, i would guess it does work. Closing
