### ISSUE TITLE
[Bug Report] <Title here>

### ISSUE THREAD

**Issue by telias82** [Merathilis/ElvUI_MerathilisUI#32]
### What is the issue you are having?

upon loading into the game there is a a warning:

[11:15] MerathilisUI  [WARNING] [Compatibility] database path not found
db.ElvUI_EltreumUI.gradientmode.npenable 

### What is the expected behavior?

not to have this happen? lol

### What actually happened?

nothing as far as i can tell, but was told to report this to you.

### Suggested Solution/Workaround

adjust the path

### Errors

```shell
[11:15] MerathilisUI  [WARNING] [Compatibility] database path not found
db.ElvUI_EltreumUI.gradientmode.npenable
```

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/Merathilis/ElvUI_MerathilisUI/blob/development/CHANGELOG.md) and done the [Troubleshooting Steps](https://github.com/Merathilis/ElvUI_MerathilisUI/wiki/Troubleshooting).

**Comment by Merathilis** [comment]
yea... I know haven't committed it yet

**Comment by eltreum0** [comment]
> yea... I know haven't committed it yet

use **db.ElvUI_EltreumUI.unitframes.gradientmode.npenable** and it should work

**Comment by Merathilis** [comment]
Fixed with the commit above ^

will be part of the next release.
