### ISSUE TITLE
[Bug Report] Battleground Queue button missing from minimap.

### ISSUE THREAD

**Issue by Fingel** [Merathilis/ElvUI_MerathilisUI#33]
### What is the issue you are having?

When queued for a battleground in TBC-Classic, the battleground queue icon is missing from the minimap.

The icon DOES appear the first time you queue, but after leaving or entering a battleground, it does not appear on subsequent queues. /reload does not seem to solve the issue.

To test this, I queued for a battleground, then left the queue. I then queued again. The minimap icon was then missing. I disabled Merathilis ui, and took a screenshot showing that the icon does appear with Merathalis ui disabled:

<img width="1235" alt="icon" src="https://user-images.githubusercontent.com/3046397/186988194-6b367d70-400e-4a08-8301-c6e2116794e8.PNG">

Then I re-enabled Merathalis UI, and took this screenshot with it missing:
<img width="1212" alt="noicon" src="https://user-images.githubusercontent.com/3046397/186988432-1cbe4a14-ec72-4eef-b6b4-db6271853719.PNG">

### What is the expected behavior?

The BG queue icon appears in the minimap.

### What actually happened?

The BG queue icon does no appear in the minimap.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/Merathilis/ElvUI_MerathilisUI/blob/development/CHANGELOG.md) and done the [Troubleshooting Steps](https://github.com/Merathilis/ElvUI_MerathilisUI/wiki/Troubleshooting).

**Comment by Merathilis** [comment]
First off all, please test it by disabling my: Modules - Maps - Minimap Buttons - untick "Enable", if that works then please type in chat: `/fstack` and mouse over the icon and make a screenshot pls. You can send the Screenshot here or discord (but pls. ping me there)

**Comment by Fingel** [comment]
Here it is: 
![WoWScrnShot_090322_221734](https://user-images.githubusercontent.com/3046397/188298647-d898fb82-a24c-402f-a9fe-9df7d1d269c2.jpg)
