### ISSUE TITLE
Spell Feedback issues

### ISSUE THREAD

**Issue by VaporAPX** [Merathilis/ElvUI_MerathilisUI#34]
### What is the issue you are having?

Cannot disable spell feedback/key feedback. Doing so reload's the UI, but the options are re-enabled after reload. Having spell feedback enabled causes conflict with Omnicc addon. The cooldown timers from the mod no longer show on my weakaura buttons and only show on the spell feedback button when enabled. Disabling the UI fixes the problem.

### What is the expected behavior?

Should be able to disable spell/key feedback, and not have any conflict with the Omnicc cooldown addon.

### What actually happened?

As stated above, cannot disable spell/key feedback and having it enabled causes Omnicc to not show cooldown numbers on my weakauras, only the newly created button from feedback.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/Merathilis/ElvUI_MerathilisUI/blob/development/CHANGELOG.md) and done the [Troubleshooting Steps](https://github.com/Merathilis/ElvUI_MerathilisUI/wiki/Troubleshooting).

**Comment by VaporAPX** [comment]
Upon further testing, having feedback enabled still has the Omnicc cooldown numbers showing on actionbars. It only seems to remove them from weakauras.

**Comment by VaporAPX** [comment]
Reverted back to 5.20. Spell feedback allows me to disable and does not cause any conflicts.  Whatever changed from Spell feedback in 5.20 and keyfeedback in 5.21 is the issue.

**Comment by Merathilis** [comment]
This is already fixed in my dev. version. I just forgot to remove the old options for it, just scroll a bit down in the ActionBar options and you find the new options.

**Comment by VaporAPX** [comment]
I downloaded the dev version and tried that as well. The option to remove Spell feedback is gone, but disabling Key Feed back still causes the issue with Omnicc. It does however disable the keyfeedback frame from showing.

**Comment by Merathilis** [comment]
Keyfeedback hast nothing to do with it, look under Skins/AddOns and untick WeakAura Cooldowns

**Comment by VaporAPX** [comment]
That did indeed fix it. Apologies, it seemed like the issue was stemming from the keyfeedback option as this was the only thing I noticed to be different. Thanks for your time and hard work. Love the layout.
