### ISSUE TITLE
My friend couldn't find where to disable the raidmarkers of MerathilisUI V.5.22...

### ISSUE THREAD

**Issue by Alarzzf** [Merathilis/ElvUI_MerathilisUI#36]
### What is the issue you are having?

![QQ图片20220906135713](https://user-images.githubusercontent.com/43119930/188557688-0f47d0ee-3db8-46a5-afa7-f3b9d6a0696c.jpg)

### What is the expected behavior?

I tried to help him find it but I failed....

### What actually happened?

He don't want to show the raidmarkers

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/Merathilis/ElvUI_MerathilisUI/blob/development/CHANGELOG.md) and done the [Troubleshooting Steps](https://github.com/Merathilis/ElvUI_MerathilisUI/wiki/Troubleshooting).
- [X] I have disabled all addons except the AddOns called 'ElvUI' and 'ElvUI OptionsUI' and 'ElvUI_MerathilisUI' by using `/muidebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and/or MerathilisUI and another addon, make sure you include that information.
- [X] I have verfied my issue doesn't exist in the default UI.

**Comment by Merathilis** [comment]
Its fixed in my dev. version. Forgot to change some option. My bad

**Comment by Alarzzf** [comment]
You can never imagine how much I doubted my intelligence and eyes before this/doge/doge/doge
