### ISSUE TITLE
[Bug Report] <Title here>

### ISSUE THREAD

**Issue by reyard** [Merathilis/ElvUI_MerathilisUI#37]
### What is the issue you are having?

I'm playing with spanish game, your locale file says esMX but it is itIT (Italian language).

### What is the expected behavior?

Interface should appear in spanish language or english, spanish is so different from Italian. Italian is not readable for spanish users.

### What actually happened?

esMX and esES are missing.

### Suggested Solution/Workaround

If you are unable to translate it, then english is fine.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/Merathilis/ElvUI_MerathilisUI/blob/development/CHANGELOG.md) and done the [Troubleshooting Steps](https://github.com/Merathilis/ElvUI_MerathilisUI/wiki/Troubleshooting).
- [X] I have disabled all addons except the AddOns called 'ElvUI' and 'ElvUI OptionsUI' and 'ElvUI_MerathilisUI' by using `/muidebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and/or MerathilisUI and another addon, make sure you include that information.
- [X] I have verfied my issue doesn't exist in the default UI.

**Comment by Merathilis** [comment]
lol.. Copy & Paste was strong with me

**Comment by Merathilis** [comment]
wait, it should be spanish tho

**Comment by Merathilis** [comment]
![image](https://user-images.githubusercontent.com/272403/189853237-b9e1ce27-6cfb-4c46-9053-1411d130de70.png)

**Comment by Merathilis** [comment]
where do you see even italien language in game?

**Comment by reyard** [comment]
![Clover_jhqEm5wcj6](https://user-images.githubusercontent.com/10302609/189873379-3bc0c94e-e182-44ef-a0ea-50d31ca5c2fc.png)
![FSViewer_H8aVECxsPX](https://user-images.githubusercontent.com/10302609/189873447-366e9d8e-5049-42ce-bdb5-c78b7aebf898.png)
