### ISSUE TITLE
[Feature Request] <Title here>

### ISSUE THREAD

**Issue by haazill** [Merathilis/ElvUI_MerathilisUI#45]
**Is your feature request related to a problem? Please describe.**
< A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] >
Hello, I wanted to know if there is a filter to show on the items in the bags if they are BOE, VIN (used in vindict set for ex.), PVP, etc...

**Describe the solution you'd like**
< A clear and concise description of what you want to happen. >
Showing on items in bags if they are BOE, VIN (used in vindict set for ex.), PVP, etc..
**Describe alternatives you've considered**

< A clear and concise description of any alternative solutions or features you've considered. >
I use normal elvui bags

Thx for your answer and for your addon which is very nice and useful ;)

phil

**Comment by Merathilis** [comment]
Its already doing that. And please, for simple question, just join my discord

**Comment by haazill** [comment]
ok thx for answer.
