### ISSUE TITLE
[Bug Report] <Title here>

### ISSUE THREAD

**Issue by haazill** [Merathilis/ElvUI_MerathilisUI#46]
### What is the issue you are having?

Hi, so thx for your work that i cannot play without now cause it's simply too nice ;)
So i have an issue with, for the moment, only one char.
I have tested without addon, no problem, with elvui, np and it's when i turn on Merathilis that i have the issue.
In chat, general, it spam an issue message which says : "oUF_GCD: Missing Spell data"
it spam everytime i made an action (attack, but also open a chest, etc)
Thx for your help and have a nice continuation ;)

phil

### What is the expected behavior?

In chat, no message spam

### What actually happened?

In chat, general, it spam an issue message which says : "oUF_GCD: Missing Spell data"

### Suggested Solution/Workaround

command /muierror does nothing
maybe an option i turn on

### Errors

```shell
In chat, general, it spam an issue message which says : "oUF_GCD: Missing Spell data"
```

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/Merathilis/ElvUI_MerathilisUI/blob/development/CHANGELOG.md) and done the [Troubleshooting Steps](https://github.com/Merathilis/ElvUI_MerathilisUI/wiki/Troubleshooting).
- [X] I have disabled all addons except the AddOns called 'ElvUI' and 'ElvUI OptionsUI' and 'ElvUI_MerathilisUI' by using `/muidebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and/or MerathilisUI and another addon, make sure you include that information.
- [X] I have verfied my issue doesn't exist in the default UI.

**Comment by Merathilis** [comment]
Which Race, Class, Specialisation are you on?

**Comment by haazill** [comment]
So i'm on paladin horde blood elf and i saw it's an addon skin which has pb, cause when i desactive addon skins, no more pb.

**Comment by haazill** [comment]
So i tried with all skins and it appears there is no problem when the skin of Ace is desactivated in MarathilisUi > Skins/Addons > AddonSkins > uncheck Ace3 and it is no more message/spam

**Comment by Merathilis** [comment]
the error should not be related to a skin at all.

**Comment by haazill** [comment]
ok don't know, but just when i disable it, it's not message/spam again in the chat
