### ISSUE TITLE
[Bug Report] <Not shown items level>

### ISSUE THREAD

**Issue by SetariaG** [Merathilis/ElvUI_MerathilisUI#47]
### What is the issue you are having?

Not shown items level.
![image](https://user-images.githubusercontent.com/22421424/198899765-c66a0ce7-76c5-4205-b4d6-dc9d11fb7803.png)

### What is the expected behavior?

Not shown items level.

### What actually happened?

Not shown items level.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/Merathilis/ElvUI_MerathilisUI/blob/development/CHANGELOG.md) and done the [Troubleshooting Steps](https://github.com/Merathilis/ElvUI_MerathilisUI/wiki/Troubleshooting).
- [X] I have disabled all addons except the AddOns called 'ElvUI' and 'ElvUI OptionsUI' and 'ElvUI_MerathilisUI' by using `/muidebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and/or MerathilisUI and another addon, make sure you include that information.
- [X] I have verfied my issue doesn't exist in the default UI.

**Comment by Merathilis** [comment]
This is already fixed in my dev. version. Thanks for the report tho.
