### ISSUE TITLE
[Bug Report] <Autobars>

### ISSUE THREAD

**Issue by Modreyn** [Merathilis/ElvUI_MerathilisUI#48]
### What is the issue you are having?

Clicking autobar items (potions, food, openable boxes) does nothing.

Should mention that this feature worked fine before I updated MUI via the TUKUI client

### What is the expected behavior?

You click autobar items and they are used (eat, drink, use potion etc)

### What actually happened?

Nothing

### Suggested Solution/Workaround

No clue lol

### Errors

```shell
I am not getting an error.

/muierror on is not working

/muidebug on is working
```

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/Merathilis/ElvUI_MerathilisUI/blob/development/CHANGELOG.md) and done the [Troubleshooting Steps](https://github.com/Merathilis/ElvUI_MerathilisUI/wiki/Troubleshooting).
- [X] I have disabled all addons except the AddOns called 'ElvUI' and 'ElvUI OptionsUI' and 'ElvUI_MerathilisUI' by using `/muidebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and/or MerathilisUI and another addon, make sure you include that information.
- [X] I have verfied my issue doesn't exist in the default UI.

**Comment by Merathilis** [comment]
Please update ElvUI. And also, for simple questions, you could also just join my Discord Server.

**Comment by Modreyn** [comment]
> Please update ElvUI. And also, for simple questions, you could also just join my Discord Server.

I tried joining from the link on tukui, but it is an expired link :( I would have though :P

**Comment by Merathilis** [comment]
> > Please update ElvUI. And also, for simple questions, you could also just join my Discord Server.
> 
> I tried joining from the link on tukui, but it is an expired link :( I would have though :P

should work again >.>
