### ISSUE TITLE
[Bug Report] <Nothing happen when click or try to open something>

### ISSUE THREAD

**Issue by haazill** [Merathilis/ElvUI_MerathilisUI#51]
### What is the issue you are having?

Hello, 
I am on retail, server EU, and since an update this evening, nothing happen when i click on a button or menu, idem with shortcuts.
When i disable merathilis (i have elvui, addonskin and benkui), all is working fine.

I tried to reinstall since elvui, and with only elvui and merathilis

### What is the expected behavior?

Open the differents windows (menu, lfr, adventurer's guide, etc...)

### What actually happened?

Nothing happen when i try to open it, with click and shortcuts same

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/Merathilis/ElvUI_MerathilisUI/blob/development/CHANGELOG.md) and done the [Troubleshooting Steps](https://github.com/Merathilis/ElvUI_MerathilisUI/wiki/Troubleshooting).
- [X] I have disabled all addons except the AddOns called 'ElvUI' and 'ElvUI OptionsUI' and 'ElvUI_MerathilisUI' by using `/muidebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and/or MerathilisUI and another addon, make sure you include that information.
- [X] I have verfied my issue doesn't exist in the default UI.

**Comment by Merathilis** [comment]
You need to enable (if its not on your end) in ElvUI - ActionBars - General - Key Down again
