### ISSUE TITLE
[Bug Report] Zygor Guides causes client crash

### ISSUE THREAD

**Issue by kodewulf** [Merathilis/ElvUI_MerathilisUI#53]
### What is the issue you are having?

Using "/reload", "/console reload", [MENU] > Logoff or [MENU] > Exit results in WoW client crash.

### What is the expected behavior?

Client should reload, logoff or exit.

### What actually happened?

Game client crashes. This only happens when 'ElvUI_MerathilisUI' is enabled.  Zero issue with default UI, or any other addons are enabled.

### Suggested Solution/Workaround

Disable the addon.  

### Errors

```shell
No errors, just game client crash.
```

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/Merathilis/ElvUI_MerathilisUI/blob/development/CHANGELOG.md) and done the [Troubleshooting Steps](https://github.com/Merathilis/ElvUI_MerathilisUI/wiki/Troubleshooting).
- [X] I have disabled all addons except the AddOns called 'ElvUI' and 'ElvUI OptionsUI' and 'ElvUI_MerathilisUI' by using `/muidebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and/or MerathilisUI and another addon, make sure you include that information.
- [X] I have verfied my issue doesn't exist in the default UI.

**Comment by Merathilis** [comment]
Do you play on classic, wotlk or retail? Also you said, it crashes if my plugin is enabled, but checked that you have tested it with /muidebug on?

Please type in chat: `/muidebug on` after the reload type in chat: `/estatus` and post me a full ui screenshot.

Hint. you could just join my discord, which is easier for support.

**Comment by kodewulf** [comment]
This issue seems to be confined to Retail. Using the most recent version of MerathilisUI and Zygor on WotLK does not produce any issues.

After enabling all my addons one at a time I think I tracked down the conflict.  It doesn't matter if only ElvUI and MerathilisUI is enabled or all my other addons, as soon as Zygor8 is loaded with MerathilisUI it results in a crash. 

It also doesn't seem to have popped up on the Zygor forums, so I have no idea what causes the conflict. I have also deleted any saved variable files from the WTF folder for both addons.

It might be work downgrading this report, but keeping open in case anybody else might shed some light on the issue.

Note: There doesn't seem to be any UI errors when the two addons are loaded separate or together.

**Comment by Merathilis** [comment]
yes, Zygor try to create such a large file for what ever reason. Anyways, if you provide me an error I can look at it. I also don't use Zygor as I don't support paid service

**Comment by kodewulf** [comment]
I'll keep an eye on it and will let you know if it gets resolved. If anybody else raises this issue, it might be worth directing them here. :)

**Comment by kodewulf** [comment]
Although this deals with Zygor and Bagnon, it might be related.  From the post it seems the problem is purely an issue with Zygor.

[Memory leak with Zygor and Bagnon](https://zygorguides.com/forum/forum/technical-support/zygor-guide-viewer/189985-memory-leak-with-zygor-and-bagnon?p=190008#post190008url)

**Comment by Merathilis** [comment]
Yes, what i said. Zygor creates a huge file which causes this crash.

**Comment by kodewulf** [comment]
Initial testing shows that this seems to have been fixed in version 8.1.27896 by the Zygor dev team for now.

**Comment by Merathilis** [comment]
Closing it, since Zygor will/ or has already fixed this.
