### ISSUE TITLE
Please stop the annoying spell alert module

### ISSUE THREAD

**Issue by ecrasy** [Merathilis/ElvUI_MerathilisUI#55]
it is bug and so fucking annoying

**Comment by ecrasy** [comment]
it wont go away
i have to roll back to the older version

**Comment by Merathilis** [comment]
First, do not hyjack my issue tracker for simple Questions.
Second: No.

**Comment by haazill** [comment]
seems i'm not alone.....it's not a question but a bug how spam chat....

**Comment by Merathilis** [comment]
> seems i'm not alone.....it's not a question but a bug how spam chat....

if you provide me proper informations and fill up the bug report template, then I might look at it.
