### ISSUE TITLE
[Feature Request] <Title here>

### ISSUE THREAD

**Issue by khoinoor** [Merathilis/ElvUI_MerathilisUI#56]
**Is your feature request related to a problem? Please describe.**
< A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] >

**Describe the solution you'd like**
< A clear and concise description of what you want to happen. >

**Describe alternatives you've considered**
< A clear and concise description of any alternative solutions or features you've considered. >

**Additional context**
< Add any other context or screenshots about the feature request here. >

Hello, since last update, I'm no longer able to use the micro menu buttons. When I mouse over them the tooltip appears like usual, but nothing happen when I click them. The only one that is working is the clock that lead to the calendar.

Thx so much for all yuour hard and amazing work .. hope u can fix it soon

**Comment by Merathilis** [comment]
This is not a future request at all, please choose the Bug Report Template next time. Or just join my discord, which would be the easiest and fastes support.

You need to change the Bug Fix in: Information
