### ISSUE TITLE
[Feature Request] <Title here>

### ISSUE THREAD

**Issue by haazill** [Merathilis/ElvUI_MerathilisUI#57]
Hello, since yesterday, I can't click on the auto buttons anymore. I think I have seen other people with the same problem.
I didn't touch anything, just did the majs.
I am available for information or other.
Thanks in advance for your answer.

**Comment by Merathilis** [comment]
This is not a feature request. Just a simple question. Please do not hijack my Issue Tracker for that, for question just join my discord.

**Comment by haazill** [comment]
pfffffff you are abot ? it's not  question lol, pfff ok 
EDIT : never ask for a bug to merathilis cause is a jerk

**Comment by Merathilis** [comment]
> pfffffff you are abot ? it's not question lol, pfff ok EDIT : never ask for a bug to merathilis cause is a jerk

First off all, you are using the "Feature Request" Template for your Topic. If you thing, this is a bug you should had use the "Bug Report" Template to open an issue. Which tells me, that you are not even able to read how to deal with stuff, which is kind off a dispresept to me, to begin with. 

Also, you gave me 0 informations that are required.

Second off all, its been asked multiple times on my discord and also answered multiple times.
