### ISSUE TITLE
Pb with reset of dpsmeters

### ISSUE THREAD

**Issue by giloup39** [Merathilis/ElvUI_MerathilisUI#59]
**Is your feature request related to a problem? Please describe.**
Yes, when i want to reset dpsmeter (recount and skada tested), it appears the title "Do you want to reset ..." but not the "yes" and "no" (it's empty) and i'm forced to reload for this go out

**Describe the solution you'd like**
"yes" and "no" appear

**Describe alternatives you've considered**
forced to reload

**Additional context**
tested with recount and skada

**Comment by Merathilis** [comment]
Please do not hijak my ticket tracker for question. You gave me 0 information about what your issue is. No Versions Nr. from ElvUI, not the Versions Nr. from me.. nothing.

If you have questions, join my discord.

**Comment by giloup39** [comment]
All is updated

**Comment by Merathilis** [comment]
I will not answer you here, sorry.

**Comment by giloup39** [comment]
Why you say is a question ? it's something which does not work....so i 'll go discord but lol

**Comment by giloup39** [comment]
ok
