### ISSUE TITLE
[Bug Report] 1x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI_MerathilisUI

### ISSUE THREAD

**Issue by Vilogity** [Merathilis/ElvUI_MerathilisUI#62]
### What is the issue you are having?

In Group with my Hunter

### What is the expected behavior?

idk

### What actually happened?

LUA Error when ply in a group

### Errors

```shell
1x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI_MerathilisUI' hat versucht die geschützte Funktion 'CompactPartyFrame:SetShown()' aufzurufen.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetShown'
[string "@Interface/FrameXML/CompactPartyFrame.lua"]:24: in function `CompactPartyFrame_UpdateVisibility'
[string "@Interface/AddOns/Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameManager.lua"]:416: in function `CompactRaidFrameManager_UpdateContainerVisibility'
[string "@Interface/AddOns/Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameManager.lua"]:69: in function <...mpactRaidFrames/Blizzard_CompactRaidFrameManager.lua:64>
[string "=[C]"]: in function `CompactRaidFrameManager_UpdateShown'
[string "@Interface/FrameXML/RaidFrame.lua"]:135: in function `UpdateRaidAndPartyFrames'
[string "@Interface/FrameXML/UIParent.lua"]:1766: in function <Interface/FrameXML/UIParent.lua:1362>
```

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/Merathilis/ElvUI_MerathilisUI/blob/development/CHANGELOG.md) and done the [Troubleshooting Steps](https://github.com/Merathilis/ElvUI_MerathilisUI/wiki/Troubleshooting).
- [X] I have disabled all addons except the AddOns called 'ElvUI' and 'ElvUI OptionsUI' and 'ElvUI_MerathilisUI' by using `/muidebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and/or MerathilisUI and another addon, make sure you include that information.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I gave you information above on which XPack i play Classic, WotLK or Retail.

**Comment by Merathilis** [comment]
This is not a really lua error.. its a taint and mostly blame the wrong AddOn. https://www.tukui.org/forum/viewtopic.php?f=5&t=9344
