### ISSUE TITLE
Microbar

### ISSUE THREAD

**Issue by Tineymage** [Merathilis/ElvUI_MerathilisUI#63]
### What is the issue you are having?

Updated to newest Elvui 13.02 and got an error message when logging in, was fine before updating this, no other addon updates. Saw 13.03 was out now updated to it, still same error. Click to ignore it but it keeps popping up every min, something in Micro Bar is clashing with RC Lootcouncil. on Classic Wrath. I disable RC and I get a difference error message about Microbar. 

### What is the expected behavior?

No error message?

### What actually happened?

Explained in what issue are you having box. 

### Errors

```shell
Message: ...lvUI_MerathilisUI\Core\Modules\MicroBar\MicroBar.lua:309: bad argument #2 to 'SetFormattedText' (string expected, got no value)
Time: Thu Nov 17 18:13:19 2022
Count: 40
Stack: ...lvUI_MerathilisUI\Core\Modules\MicroBar\MicroBar.lua:309: bad argument #2 to 'SetFormattedText' (string expected, got no value)
[string "@Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua"]:146: in function <...tCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:144>
[string "=[C]"]: ?
[string "=[C]"]: in function `SetFormattedText'
[string "@Interface\AddOns\ElvUI_MerathilisUI\Core\Modules\MicroBar\MicroBar.lua"]:309: in function <...lvUI_MerathilisUI\Core\Modules\MicroBar\MicroBar.lua:303>

Locals: private = <table> {
 ThrowError = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:46
 DoesErrorExist = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:87
 ClearOldErrors = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:107
 SanitizeLine = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:83
 MAX_STACK_DEPTH = 10
 log = <table> {
 }
 ErrorHandler = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:116
 IncrementErrorCount = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:77
 NewError = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:50
 IsRCLootCouncilError = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:94
}
orig_errorhandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355



This message pops up if I disable RC Lootcouncil


Message: ...lvUI_MerathilisUI\Core\Modules\MicroBar\MicroBar.lua:309: bad argument #2 to 'SetFormattedText' (string expected, got no value)
Time: Thu Nov 17 18:19:09 2022
Count: 8
Stack: ...lvUI_MerathilisUI\Core\Modules\MicroBar\MicroBar.lua:309: bad argument #2 to 'SetFormattedText' (string expected, got no value)
[string "=[C]"]: ?
[string "=[C]"]: in function `SetFormattedText'
[string "@Interface\AddOns\ElvUI_MerathilisUI\Core\Modules\MicroBar\MicroBar.lua"]:309: in function <...lvUI_MerathilisUI\Core\Modules\MicroBar\MicroBar.lua:303>
```

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/Merathilis/ElvUI_MerathilisUI/blob/development/CHANGELOG.md) and done the [Troubleshooting Steps](https://github.com/Merathilis/ElvUI_MerathilisUI/wiki/Troubleshooting).
- [X] I have disabled all addons except the AddOns called 'ElvUI' and 'ElvUI OptionsUI' and 'ElvUI_MerathilisUI' by using `/muidebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and/or MerathilisUI and another addon, make sure you include that information.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I gave you information above on which XPack i play Classic, WotLK or Retail.

**Comment by Merathilis** [comment]
ElvUI version is in this case irrelevant, you dont mentioned my verion tho ^^

**Comment by Tineymage** [comment]
5.39

**Comment by Tineymage** [comment]
Been watching if something triggers it. The count for the error happening goes up everytime one of my guild members come online or go offline.

**Comment by Tineymage** [comment]
Turning off system notifications for when people come on and offline has stopped the errors.

**Comment by Merathilis** [comment]
This should be fixed with my latest verison
