### ISSUE TITLE
[Bug Report] Retail Bag closes after interaction

### ISSUE THREAD

**Issue by SolidBrave** [Merathilis/ElvUI_MerathilisUI#64]
### What is the issue you are having?

After having any interaction with the bags it closes afterwards.
elvui: 13.08 
MeathilisUI: 5.45

### What is the expected behavior?

Bag Frame should stay open.

### What actually happened?

Bag Frame closes

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/Merathilis/ElvUI_MerathilisUI/blob/development/CHANGELOG.md) and done the [Troubleshooting Steps](https://github.com/Merathilis/ElvUI_MerathilisUI/wiki/Troubleshooting).
- [X] I have disabled all addons except the AddOns called 'ElvUI' and 'ElvUI OptionsUI' and 'ElvUI_MerathilisUI' by using `/muidebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and/or MerathilisUI and another addon, make sure you include that information.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I gave you information above on which XPack i play Classic, WotLK or Retail.

**Comment by Merathilis** [comment]
You have 100% another AddOn that is messing with it. Please confirm it after you type in /muidebug on

**Comment by SolidBrave** [comment]
I of course did check this aswell. So now I am confused ^^
https://www.youtube.com/watch?v=IYozf9H1ni8

**Comment by Merathilis** [comment]
Send me your profile please, since i still cant find a way to reproduce this.

FYI: You still have the ElvUI_OptionsUI AddOn in your AddOn folder you can delete that, it got renamed to ElvUI_Options

**Comment by SolidBrave** [comment]
oh wow deleting ElvUI_OptionsUI resolved it.

**Comment by Merathilis** [comment]
Okay, dont know that it cause it. thx for the heads up

**Comment by SolidBrave** [comment]
@Merathilis hmm I managed to replicate it again by disabling "Bag Bar" in ElvUI...

**Comment by Merathilis** [comment]
I also have it disabled and still dont have it D:

**Comment by SolidBrave** [comment]
[tarrasqProfileDefault.txt](https://github.com/Merathilis/ElvUI_MerathilisUI/files/10148505/tarrasqProfileDefault.txt)

**Comment by Merathilis** [comment]
hm.. still seems fine on my end 🤔 i had some others reporting this, but i have absolute no clue.

could be a profile only thing on your end

**Comment by SolidBrave** [comment]
I gonna keep it for now with the bagbar active, so long I dont encounter any more issue I gonna keep it that way.

**Comment by SolidBrave** [comment]
@Merathilis Okey I assume the issue was somehow with shadow&light config also had the blizzard bank frame always on.
Had to disable MeathilisUI, enable bags, disable bagbar, then enable MeathilisUI again. Now the blizzard bank frame is gone and the bags don't close anymore with bagbar disabled.

**Comment by Merathilis** [comment]
Just disable the Blizz Mover in the S&L option

**Comment by SolidBrave** [comment]
Ehm no? I like being able to move my frames and now it works all fine for me ^^

**Comment by Merathilis** [comment]
Thats what breaks it, so i just mentioned it.
