### ISSUE TITLE
[Bug Report]  Tooltip Error switching Specs

### ISSUE THREAD

**Issue by SolidBrave** [Merathilis/ElvUI_MerathilisUI#66]
### What is the issue you are having?

Switching from Druid Restoration Spec to Guarding Spec triggeres lua errors. Using latest dev version (retail).

### What is the expected behavior?

no Lua Errors

### What actually happened?

Lua errors.

### Errors

```shell
483x .../ElvUI_MerathilisUI/Core/Modules/Tooltip/Tooltip.lua:77: bad argument #2 to 'strsplit' (string expected, got nil)
[string "=[C]"]: in function `strsplit'
[string "@ElvUI_MerathilisUI/Core/Modules/Tooltip/Tooltip.lua"]:77: in function `CheckModifier'
[string "@ElvUI_MerathilisUI/Core/Modules/Tooltip/Tooltip.lua"]:110: in function `InspectInfo'
[string "@ElvUI_MerathilisUI/Core/Modules/Tooltip/Tooltip.lua"]:175: in function <.../ElvUI_MerathilisUI/Core/Modules/Tooltip/Tooltip.lua:168>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `SetAttribute'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:282: in function <SharedXML/Tooltip/TooltipDataHandler.lua:240>
[string "=[C]"]: in function `securecallfunction'
```

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/Merathilis/ElvUI_MerathilisUI/blob/development/CHANGELOG.md) and done the [Troubleshooting Steps](https://github.com/Merathilis/ElvUI_MerathilisUI/wiki/Troubleshooting).
- [X] I have disabled all addons except the AddOns called 'ElvUI' and 'ElvUI OptionsUI' and 'ElvUI_MerathilisUI' by using `/muidebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and/or MerathilisUI and another addon, make sure you include that information.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I gave you information above on which XPack i play Classic, WotLK or Retail.

**Comment by Merathilis** [comment]
you forgot to mention that you are using "dual profiles*

**Comment by SolidBrave** [comment]
Sry what do you mean with dual profiles excacly.

**Comment by Merathilis** [comment]
You are using two different profiles.

![image](https://user-images.githubusercontent.com/272403/205736808-afae0ac1-b23a-40c3-bce9-de955d4111ea.png)
this one ^

**Comment by Merathilis** [comment]
no its a bug. and i need to figure out why this happens :x

**Comment by Merathilis** [comment]
should be fixed with the commit above
