### ISSUE TITLE
[Bug Report] Minimap icons glitch

### ISSUE THREAD

**Issue by StarkzxP** [Merathilis/ElvUI_MerathilisUI#67]
### What is the issue you are having?

This is on Retail version. Glitched icons on the top left section of the minimap, where usually the raid difficulty icons appear. Tried reinstalling elvui and merathilisui but it stays the same. Also tried "/muidebug on".
![Captura de pantalla 2022-12-10 144556](https://user-images.githubusercontent.com/11592693/206868335-3a93041b-6051-45b4-a575-218823402024.png)

### What is the expected behavior?

To not show the icons.

### What actually happened?

It started right when i installed today's update of merathilisUI from curseforge.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/Merathilis/ElvUI_MerathilisUI/blob/development/CHANGELOG.md) and done the [Troubleshooting Steps](https://github.com/Merathilis/ElvUI_MerathilisUI/wiki/Troubleshooting).
- [X] I have disabled all addons except the AddOns called 'ElvUI' and 'ElvUI OptionsUI' and 'ElvUI_MerathilisUI' by using `/muidebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and/or MerathilisUI and another addon, make sure you include that information.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I gave you information above on which XPack i play Classic, WotLK or Retail.

**Comment by Merathilis** [comment]
Also, already fixed
