### ISSUE TITLE
[Bug Report] Quests count on the objective frame still show the old limit

### ISSUE THREAD

**Issue by eloxole** [Merathilis/ElvUI_MerathilisUI#68]
### What is the issue you are having?

The quest count still shows the old limit (25). Also, this quest count only shows up on some characters and not all. I cannot find any setting for turning this on or off the UI config. Even if characters use the same profile, some will have quest count and some don't.

Tested if this is caused by MerathilisUI, I disabled all addons, the quest count disappeared. Then only turn on Elvui alone, no quest count. Added MerathilisUI and it appears.

### What is the expected behavior?

Should be updated to 35. The display of the quest count should be consistent.

### What actually happened?

![WoWScrnShot_121122_155918](https://user-images.githubusercontent.com/100048099/206928952-7db9928d-8d9d-4acf-9322-bccbb541ea26.jpg)

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/Merathilis/ElvUI_MerathilisUI/blob/development/CHANGELOG.md) and done the [Troubleshooting Steps](https://github.com/Merathilis/ElvUI_MerathilisUI/wiki/Troubleshooting).
- [X] I have disabled all addons except the AddOns called 'ElvUI' and 'ElvUI OptionsUI' and 'ElvUI_MerathilisUI' by using `/muidebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and/or MerathilisUI and another addon, make sure you include that information.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I gave you information above on which XPack i play Classic, WotLK or Retail.

**Comment by Merathilis** [comment]
it only show up 2hen the quest log is almost full. Type in chat: `/dump MAX_QUESTS` then you will see what the API returns.
