### ISSUE TITLE
[Bug Report] Crash on startup for 1 out of 34 characters

### ISSUE THREAD

**Issue by blakebarnett** [Merathilis/ElvUI_MerathilisUI#69]
### What is the issue you are having?

Crash at the end of loading the game 100% of the time for a specific character.
Retail game, dragon flight 10.0.2 47213
ElvUI version: 13.17
MerethilisUI version: 5.55

### What is the expected behavior?

The game loads with the add-on enabled.

### What actually happened?

When I start the game with ElvUI_MerethilisUI enabled for a level 50 male Mag'har Orc Warrior, it crashes at the end of loading every time. If I disable it, the game loads fine. I have ElvUI, Shadows & Light and MerethilisUI working for for all 33 other characters. If I create a new level 1 character with very similar looks, it loads fine.

This character is very old, I created it just after release, might have something to do with it? I tried clearing out all the character data at one point, but it still happens.

### Suggested Solution/Workaround

I tried turning on /muidebug on another character and then loading, but it still just crashes and nothing new is added to any of the wow logs.

### Errors

```shell
I'm not really sure how to debug it, I don't see anything in the wow logs about it. I tried turning on DEBUG logging in the MerethilisUI advanced settings, but it doesn't seem to help.
```

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/Merathilis/ElvUI_MerathilisUI/blob/development/CHANGELOG.md) and done the [Troubleshooting Steps](https://github.com/Merathilis/ElvUI_MerathilisUI/wiki/Troubleshooting).
- [X] I have disabled all addons except the AddOns called 'ElvUI' and 'ElvUI OptionsUI' and 'ElvUI_MerathilisUI' by using `/muidebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and/or MerathilisUI and another addon, make sure you include that information.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I gave you information above on which XPack i play Classic, WotLK or Retail.

**Comment by blakebarnett** [comment]
Maybe worth mentioning that this character has been server transferred multiple times, and had a race change from regular Orc to Mag'har.

**Comment by Merathilis** [comment]
Thats really weird, backup your wtf folder and try it with a fresh one please

**Comment by blakebarnett** [comment]
No luck, I tried this a while back also with the same result. The only other piece of info I have is the crash dump if you're interested?

**Comment by Merathilis** [comment]
Yes, please
