### ISSUE TITLE
[Bug Report] elvui plugin not loading

### ISSUE THREAD

**Issue by muldev** [Merathilis/ElvUI_MerathilisUI#72]
### What is the issue you are having?

RE: Worldofwarcraft Retail (Dragonfilght)
After a recent wow update on the 17/01/2023 ElvUI MerathilisUI is not loading as a plugin. Strangely enough, the AFK works and displays the  MerathilisUI add, however, no other features work and it is not listed in the elvui plugins.

### What is the expected behavior?

I expect the ElvUI MerathilisUI to load as a plugin.

### What actually happened?

After an Elvui update released on 18/01/2023

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/Merathilis/ElvUI_MerathilisUI/blob/development/CHANGELOG.md) and done the [Troubleshooting Steps](https://github.com/Merathilis/ElvUI_MerathilisUI/wiki/Troubleshooting).
- [X] I have disabled all addons except the AddOns called 'ElvUI' and 'ElvUI OptionsUI' and 'ElvUI_MerathilisUI' by using `/muidebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and/or MerathilisUI and another addon, make sure you include that information.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I gave you information above on which XPack i play Classic, WotLK or Retail.

**Comment by Azilroka** [comment]
You didn't do `/muidebug on`

**Comment by reyard** [comment]
Same for me.

**Comment by Merathilis** [comment]
What Azilroka wrote, please do what mention above, you checked it that you have done it already, but apparently you havent.

**Comment by reyard** [comment]
elvui Merathilis + elvui chat tweaks at same time doesn't work, elvui chat tweaks disable to elvui merathilis

**Comment by reyard** [comment]
It says the bug report when merathilis and chat tweaks are working at same.

2x ElvUI/Core/General/Core.lua:379: attempt to call local 'func' (a boolean value)
[string "@ElvUI/Core/General/Core.lua"]:379: in function `ValueFuncCall'
[string "@ElvUI/Core/General/Core.lua"]:331: in function <ElvUI/Core/General/Core.lua:277>
[string "=[C]"]: in function `UpdateMedia'
[string "@ElvUI/Core/General/Core.lua"]:1949: in function <ElvUI/Core/General/Core.lua:1915>
[string "=[C]"]: in function `Initialize'
[string "@ElvUI/Core/init.lua"]:223: in function <ElvUI/Core/init.lua:222>
[string "=[C]"]: ?
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:538: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:743: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:100: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:93: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:88: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:80: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:76>
[string "=[C]"]: ?
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

**Comment by Merathilis** [comment]
Which means the error comes from Chat Tweaks
