### ISSUE TITLE
DC klappt irgendwie nicht mehr sorry, kein Chan mehr verfügbar...........

### ISSUE THREAD

**Issue by Vilogity** [Merathilis/ElvUI_MerathilisUI#74]
### What is the issue you are having?

Wie in gottes Namen !! kann ich die 200 Benachrichtigungen die ich bekomme wenn ich an einer Kiste oä vorbei fliege ausschalten.
Sry ichsuche mir da einen ab uind finde keine der Einstgellungen.

Vielen Danke für deine Hilfe 

### What is the expected behavior?

ja

### What actually happened?

Genau bin genervt.-.....

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/Merathilis/ElvUI_MerathilisUI/blob/development/CHANGELOG.md) and done the [Troubleshooting Steps](https://github.com/Merathilis/ElvUI_MerathilisUI/wiki/Troubleshooting).
- [X] I have disabled all addons except the AddOns called 'ElvUI' and 'ElvUI OptionsUI' and 'ElvUI_MerathilisUI' by using `/muidebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and/or MerathilisUI and another addon, make sure you include that information.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I gave you information above on which XPack i play Classic, WotLK or Retail.

**Comment by Merathilis** [comment]
bitte für simple Fragen kein Ticket eröffnen, dafür gibt es Discord.

**Comment by Vilogity** [comment]
Hallo Mein lieber 
Ich war schon zoig mal bei dir drine, es geht nicht mehr, ich sehe keinen chan mehr und habe keine ahnung warum.....
SORRY
