### ISSUE TITLE
When browsing Dungeon/Raid groups my game freezes

### ISSUE THREAD

**Issue by Rolezyy** [Merathilis/ElvUI_MerathilisUI#75]
### What is the issue you are having?

When browing custom/dungeon/raid groups my game freeze for a few seconds, and then says "interface action failed because of an AddOn".  Thereafter, my game freezes every couple of seconds whilst scrolling through the group finders.  This obviously makes joining groups a real pain in the backside!  I play wow retail btw!

### What is the expected behavior?

To be able to scroll smoothly without my game crashing

### What actually happened?

See first box.  I can do a screen record if you need it!  

### Errors

```shell
2/1 20:14:07.607  Interface/FrameXML/LFGList.lua:2596
2/1 20:14:07.607  An action was blocked because of taint from ElvUI_MerathilisUI - GetPlaystyleString()
2/1 20:14:07.607      Interface/FrameXML/LFGList.lua:3522
2/1 20:14:07.607      LFGListUtil_SetSearchEntryTooltip()
2/1 20:14:07.607      Interface/FrameXML/LFGList.lua:2597
2/1 20:14:08.459  Execution tainted by ElvUI_MerathilisUI while reading INTERFACE_ACTION_BLOCKED_SHOWN - Interface/FrameXML/UIParent.lua:5301 DisplayInterfaceActionBlockedMessage()
2/1 20:14:08.459      Interface/FrameXML/UIParent.lua:1878
2/1 20:14:08.459      GetPlaystyleString()
2/1 20:14:08.459      Interface/FrameXML/LFGList.lua:3522
2/1 20:14:08.459      LFGListUtil_SetSearchEntryTooltip()
2/1 20:14:08.459      Interface/FrameXML/LFGList.lua:2597
2/1 20:14:08.459  Interface/FrameXML/LFGList.lua:2596
2/1 20:14:08.459  An action was blocked because of taint from ElvUI_MerathilisUI - GetPlaystyleString()
2/1 20:14:08.459      Interface/FrameXML/LFGList.lua:3522
2/1 20:14:08.459      LFGListUtil_SetSearchEntryTooltip()
2/1 20:14:08.459      Interface/FrameXML/LFGList.lua:2597
2/1 20:14:10.356  Execution tainted by ElvUI_MerathilisUI while reading INTERFACE_ACTION_BLOCKED_SHOWN - Interface/FrameXML/UIParent.lua:5301 DisplayInterfaceActionBlockedMessage()
2/1 20:14:10.356      Interface/FrameXML/UIParent.lua:1878
2/1 20:14:10.356      GetPlaystyleString()
2/1 20:14:10.356      Interface/FrameXML/LFGList.lua:3522
2/1 20:14:10.356      LFGListUtil_SetSearchEntryTooltip()
2/1 20:14:10.356      Interface/FrameXML/LFGList.lua:2597
2/1 20:14:10.356  Interface/FrameXML/LFGList.lua:2596
2/1 20:14:10.356  An action was blocked because of taint from ElvUI_MerathilisUI - GetPlaystyleString()
2/1 20:14:10.356      Interface/FrameXML/LFGList.lua:3522
2/1 20:14:10.356      LFGListUtil_SetSearchEntryTooltip()
2/1 20:14:10.356      Interface/FrameXML/LFGList.lua:2597
```

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/Merathilis/ElvUI_MerathilisUI/blob/development/CHANGELOG.md) and done the [Troubleshooting Steps](https://github.com/Merathilis/ElvUI_MerathilisUI/wiki/Troubleshooting).
- [X] I have disabled all addons except the AddOns called 'ElvUI' and 'ElvUI OptionsUI' and 'ElvUI_MerathilisUI' by using `/muidebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and/or MerathilisUI and another addon, make sure you include that information.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I gave you information above on which XPack i play Classic, WotLK or Retail.

**Comment by Rolezyy** [comment]
Update: if I disable Merathilis addon, but leave everything else enabled, my game doesn't freeze, so it _seems_ to be localised to the addon.

**Comment by Merathilis** [comment]
The error is not related to any freeze or lags. Its a known WoW Taint on the LFG Frame right now. Not AddOn related tho.

And disabling an AddOn prove actually nothing. I need you to give you a way to reproduce the error to me. Thats why i have my troubleshooting steps. Type in chat `/muidebug on` and then test again. But for further help on this, please join my discord.
