### ISSUE TITLE
[Bug Report]  I lost the home icons on top under the location bar

### ISSUE THREAD

**Issue by fakh2006** [Merathilis/ElvUI_MerathilisUI#76]
### What is the issue you are having?

I used to see my character icon , mail icon, and other things under the location bar, but now it is gone and I cannot get it back.

### What is the expected behavior?

To get the icons back

### What actually happened?

I dont know it stopped working

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/Merathilis/ElvUI_MerathilisUI/blob/development/CHANGELOG.md) and done the [Troubleshooting Steps](https://github.com/Merathilis/ElvUI_MerathilisUI/wiki/Troubleshooting).
- [X] I have disabled all addons except the AddOns called 'ElvUI' and 'ElvUI OptionsUI' and 'ElvUI_MerathilisUI' by using `/muidebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and/or MerathilisUI and another addon, make sure you include that information.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I gave you information above on which XPack i play Classic, WotLK or Retail.

**Comment by Merathilis** [comment]
Okay, first off all:

![image](https://user-images.githubusercontent.com/272403/217882765-8d4a2b03-a6c5-4093-b261-5062d7740273.png)
No, you haven't.

Second:
You haven't read the Changelog.
