### ISSUE TITLE
[Bug Report] <EquipSetBar not working>

### ISSUE THREAD

**Issue by MKMota** [Merathilis/ElvUI_MerathilisUI#77]
### What is the issue you are having?

EquipSetBar not working

### What is the expected behavior?

show EquipSetBar

### What actually happened?

cant see EquiSetBar

### Errors

_I dont now how to see if have any error, but EquipSetBar disappeared in a update, and i never see more. 
I did all Troubleshooting Steps but, cant see how to fix. Thanks for patience._

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/Merathilis/ElvUI_MerathilisUI/blob/development/CHANGELOG.md) and done the [Troubleshooting Steps](https://github.com/Merathilis/ElvUI_MerathilisUI/wiki/Troubleshooting).
- [X] I have disabled all addons except the AddOns called 'ElvUI' and 'ElvUI OptionsUI' and 'ElvUI_MerathilisUI' by using `/muidebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and/or MerathilisUI and another addon, make sure you include that information.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I gave you information above on which XPack i play Classic, WotLK or Retail.

**Comment by Merathilis** [comment]
That is because i removed it some time ago. Had some issues with it i could'nt get behind
