### ISSUE TITLE
[Feature Request] I hope this feature will be added.

### ISSUE THREAD

**Issue by ILIKECHICKENTOOMUCH** [Merathilis/ElvUI_MerathilisUI#78]
**Is your feature request related to a problem? Please describe.**

When a guild member log in, the icon shape and color are intuitive and easy to recognize.
But when online friends log in, nothing changes. 
I want my online friends to be intuitively visible in the chat window when they are online & offline.
In MerathilisUI version 5.1x,

L["ERR_FRIEND_ONLINE"] = "has come |cff298F00online|r."
L["ERR_FRIEND_OFFLINE"] = "has gone |cffff0000offline|r."
L["BN_INLINE_TOAST_FRIEND_ONLINE"] = " has come |cff298F00online|r."
L["BN_INLINE_TOAST_FRIEND_OFFLINE"] = " has gone |cffff0000offline|r.."

These commands changed the color of the chat window. As the version was upgraded, these disappeared. 
But I can't forget MerathilisUI when it had these features. It was very useful for me.

It would be nice if it could be seen intuitively when a battl.net friend accesses, just like when a guild member accesses.

**Comment by ILIKECHICKENTOOMUCH** [comment]
@Merathilis  
Thank you so much for adding the function I requested so quickly.
I downloaded the development version and checked out the features.

Message delay occurs as shown in the screenshot.
There is a delay when my friend is online or offline. Sometimes there is no delay.
There was no delay when the guild member accessed or exited.

![Screenshot](https://i.imgur.com/k8c0fZM.png)

**Comment by Merathilis** [comment]
yea, thats because its not finished... i also need to check a couple of things

**Comment by ILIKECHICKENTOOMUCH** [comment]
@Merathilis 
sorry. I was in too much of a hurry.
Thank you for always.

**Comment by fang2hou** [comment]
1. The icon not be rendered?
1. Currently there are two types alert: guild member alert and bnet friend alert. Because of the guild member message also have been enhanced, so I disabled the alert that the player is in your guild to avoid duplicated showing. The BNet friend status changed event which is sent from Blizzard is always a little bit delayed. There is no better solution now.

**Comment by Merathilis** [comment]
see, master has spoken

**Comment by ILIKECHICKENTOOMUCH** [comment]
@fang2hou @Merathilis 
1. The icon not be rendered?  Yes. I can see a green icon in front of my friends battle tag.
2. Personally, I liked the way it was displayed up until the last MerathilisUI 5.26 version, because it was simple. Is this not possible anymore, because the code has changed a lot now?

**Comment by fang2hou** [comment]
@ILIKECHICKENTOOMUCH 
The code is completely rewritten.
Actually, the alert about blizzard is really different:

#### before
1. Blizzard friend goes online.
    - Blizzard send this to game chat, Mera's stuff enhances the message in chat
1. Blizzard friend's WoW character goes online message.
    - No this feature
#### now
1. Blizzard friend goes online.
    -  Blizzard send this to game chat, no more enhancement now
1. Blizzard friend's WoW character goes online
    - The addon check the Blizzard's information when Blizzard told addon that the Blizzard friend's status has been changed.
    - If the status not same with cache, the addon will generate a message and send it to chat.

**Comment by Merathilis** [comment]
also @ILIKECHICKENTOOMUCH please join for an conversation my discord and don't hijack this ticket tracker ;)
