### ISSUE TITLE
[Bug Report] LUA error when loading WoW - Retail

### ISSUE THREAD

**Issue by Marangwe** [Merathilis/ElvUI_MerathilisUI#80]
### What is the issue you are having?

26x ...UI/Mainline/Modules/Skins/FrameXML/QuestMapFrame.lua:61: attempt to index field 'QuestLogPopupDetailFrameScrollFrameTop' (a nil value)
[string "@ElvUI_MerathilisUI/Mainline/Modules/Skins/FrameXML/QuestMapFrame.lua"]:61: in function <...UI/Mainline/Modules/Skins/FrameXML/QuestMapFrame.lua:8>
[string "=[C]"]: ?
[string "@ElvUI/Core/Modules/Skins/Skins.lua"]:1873: in function <ElvUI/Core/Modules/Skins/Skins.lua:1868>
[string "=[C]"]: ?
[string "@ElvUI/Core/General/Core.lua"]:1819: in function `CallLoadFunc'
[string "@ElvUI/Core/General/Core.lua"]:1834: in function `CallLoadedModule'
[string "@ElvUI/Core/General/Core.lua"]:1860: in function `InitializeModules'
[string "@ElvUI/Core/General/Core.lua"]:1970: in function <ElvUI/Core/General/Core.lua:1939>
[string "=[C]"]: in function `Initialize'
[string "@ElvUI/Core/init.lua"]:265: in function <ElvUI/Core/init.lua:264>
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
...
[string "@FrameXML/UIParent.lua"]:545: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:754: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:100: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:93: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:88: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:80: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:76>
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals:
QuestMapFrame = QuestMapFrame {
 QuestsFrame = QuestScrollFrame {
 }
 HideCampaignOverview = <function> defined @FrameXML/QuestMapFrame.lua:60
 completedCriteria = <table> {
 }
 DetailsFrame = Frame {
 }
 OnHighlightedQuestPOIChange = <function> defined @FrameXML/QuestMapFrame.lua:65
 OnMapPinClick = <function> defined @FrameXML/QuestMapFrame.lua:72
 Background = Texture {
 }
 SetFrameLayoutIndex = <function> defined @FrameXML/QuestMapFrame.lua:45
 QuestSessionManagement = Frame {
 }
 Refresh = <function> defined @FrameXML/QuestMapFrame.lua:25
 SyncQuestSystemWithCurrentMap = <function> defined @FrameXML/QuestMapFrame.lua:15
 GetCurrentMapID = <function> defined @FrameXML/QuestMapFrame.lua:7
 ResetLayoutIndex = <function> defined @FrameXML/QuestMapFrame.lua:50
 CampaignOverview = Frame {
 }
 ShowCampaignOverview = <function> defined @FrameXML/QuestMapFrame.lua:54
 UpdatePOIs = <function> defined @FrameXML/QuestMapFrame.lua:37
 0 = <userdata>
 VerticalSeparator = Texture {
 }
}
QuestScrollFrame = QuestScrollFrame {
 DetailFrame = Frame {
 }
 CampaignTooltip = Frame {
 }
 scrollBarX = 9
 objectiveFramePool = <table> {
 }
 headerFramePool = <table> {
 }
 scrollBarTopY = -4
 titleFramePool = <table> {
 }
 campaignHeaderMinimalFramePool = <table> {
 }
 campaignHeaderFramePool = <table> {
 }
 covenantCallingsHeaderFramePool = <table> {
 }
 scrollBarBottomY = 6
 0 = <userdata>
 ScrollBar = Frame {
 }
 StoryTooltip = Frame {
 }
 Edge = Texture {
 }
 Contents = Frame {
 }
}
DetailsFrame = Frame {
 0 = <userdata>
 DestinationMapButton = Button {
 }
 WaypointMapButton = Button {
 }
 AbandonButton = Button {
 }
 BackButton = Button {
 }
 ShareButton = Button {
 }
 RewardsFrame = Frame {
 }
 TrackButton = Button {
 }
 CompleteQuestFrame = Frame {
 }
 SealMaterialBG = Texture {
 }
 Bg = Texture {
 }
 ScrollFrame = QuestMapDetailsScrollFrame {
 }
}
RewardsFrame = Frame {
 0 = <userdata>
 Background = Texture {
 }
}
CompleteQuestFrame = Frame {
 0 = <userdata>
 CompleteButton = Button {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = 0
(*temporary) = <userdata>
(*temporary) = Texture {
 0 = <userdata>
 PixelSnapDisabled = true
}
(*temporary) = QuestMapFrameText {
 0 = <userdata>
 fontStyle = "OUTLINE"
 font = "Interface\AddOns\ElvUI_MerathilisUI\Core\Media\Fonts\PROTOTYPE.TTF"
 fontSize = 12
}
(*temporary) = Texture {
 0 = <userdata>
 PixelSnapDisabled = true
}
(*temporary) = Texture {
 0 = <userdata>
 PixelSnapDisabled = true
}
(*temporary) = "attempt to index field 'QuestLogPopupDetailFrameScrollFrameTop' (a nil value)"
module = <table> {
 CreateLowerShadow = <function> defined @ElvUI_MerathilisUI/Core/Modules/Skins/API.lua:93
 UpdateShadowColor = <function> defined @ElvUI_MerathilisUI/Core/Modules/Skins/API.lua:105
 ArrowRotation = <table> {
 }
 ElvUI_ActionBar_SkinButton = <function> defined @ElvUI_MerathilisUI/Core/Modules/Skins/ElvUI/ActionBars.lua:12
 ElvUI_ChatPanels = <function> defined @ElvUI_MerathilisUI/Core/Modules/Skins/ElvUI/Chat.lua:5
 ElvUI_Misc = <function> defined @ElvUI_MerathilisUI/Core/Modules/Skins/ElvUI/Misc.lua:7
 RaiderIO = <function> defined @ElvUI_MerathilisUI/Mainline/Modules/Skins/Extern/RaiderIO.lua:102
 AddCallbackForAceGUIWidget = <function> defined @ElvUI_MerathilisUI/Core/Modules/Skins/Core.lua:67
 WeakAurasNewButton = <function> defined @ElvUI_MerathilisUI/Core/Modules/Skins/Extern/WeakAurasOptions.lua:130
 SetDefaultModulePrototype = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:405
 RefreshToggleDirection = <function> defined @ElvUI_MerathilisUI/Core/Modules/Skins/API.lua:945
 LootHistoryFrame_FullUpdate = <function> defined @ElvUI_MerathilisUI/Mainline/Modules/Skins/FrameXML/LootFrame.lua:10
 OmniCD_Party_ExtraBars = <function> defined @ElvUI_MerathilisUI/Main

### What is the expected behavior?

n/a

### What actually happened?

n/a

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/Merathilis/ElvUI_MerathilisUI/blob/development/CHANGELOG.md) and done the [Troubleshooting Steps](https://github.com/Merathilis/ElvUI_MerathilisUI/wiki/Troubleshooting).
- [X] I have disabled all addons except the AddOns called 'ElvUI' and 'ElvUI OptionsUI' and 'ElvUI_MerathilisUI' by using `/muidebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and/or MerathilisUI and another addon, make sure you include that information.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I gave you information above on which XPack i play Classic, WotLK or Retail.

**Comment by Merathilis** [comment]
> * [x]  I gave you information above on which XPack i play Classic, WotLK or Retail.

No, you havent give me any information, just simply posting an error. So your issue report is invalid, next time, give me a way to reproduce it and the required informations.
