### ISSUE TITLE
LUA ERROR after Version 5.90 - BAGSYNC Retail

### ISSUE THREAD

**Issue by Vilogity** [Merathilis/ElvUI_MerathilisUI#83]
### What is the issue you are having?

Log in with 5.91 ans 5.92 then get LUA Errors from Skin in Retail last Version
No Problems with Version 5.90 !

### What is the expected behavior?

Changes in 5.91 and 5.92.....5.90 works fine

### What actually happened?

LUA Errors BAGSYNC

I dont use BAGSYNC I use Bagnon

### Suggested Solution/Workaround

Se below

### Errors

```shell
Error 1 
1x .../ElvUI_MerathilisUI/Modules/Skins/Extern/BagSync.lua:6: Usage: GetAddon(name): 'name' - Cannot find an AceAddon 'BagSync'.
[string "=[C]"]: ?
[string "@Bartender4/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:151: in function `GetAddon'
[string "@ElvUI_MerathilisUI/Modules/Skins/Extern/BagSync.lua"]:6: in main chunk

Locals:
(*temporary) = "Usage: GetAddon(name): 'name' - Cannot find an AceAddon 'BagSync'."

ERROR 2
1x ElvUI_MerathilisUI/Modules/Skins/Extern/BagSync.lua:1 (null)
ERROR 3
1x Interface\FrameXML\Bindings.xml:1 ElvUI_MerathilisUI/Modules/Skins/Extern/BagSync.lua:1 (null)
```

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/Merathilis/ElvUI_MerathilisUI/blob/development/CHANGELOG.md) and done the [Troubleshooting Steps](https://github.com/Merathilis/ElvUI_MerathilisUI/wiki/Troubleshooting).
- [X] I have disabled all addons except the AddOns called 'ElvUI' and 'ElvUI OptionsUI' and 'ElvUI_MerathilisUI' by using `/muidebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and/or MerathilisUI and another addon, make sure you include that information.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I gave you information above on which XPack i play Classic, WotLK or Retail.

**Comment by Merathilis** [comment]
Fixed with the commit above. Will be part in the next Version.

P.S. Bagnon has nothing to do with this, two complete different AddOns :>
