### ISSUE TITLE
[Bug Report] <I can't change the health backdrop>

### ISSUE THREAD

**Issue by kkarollinee** [Merathilis/ElvUI_MerathilisUI#84]
### What is the issue you are having?

I'm returning to the game this week, so i like to use health bar (ally and enemy) with the color class and black backdrop, for some reason the Merathillis plugin is overwritten the Elvui configuration making the bar the same color of the class (only a litle bit lighther see the print). I desativate the plugin and with only the Elvui, it works as pretended.
![Screenshot_1](https://github.com/Merathilis/ElvUI_MerathilisUI/assets/6808672/cbe754d8-3a3f-43f8-b02a-1cc39c9feb08)
 only the Elvui works as i like, dark backdrop.

### What is the expected behavior?

When I change the backdrop color on the Elvui menu unitframes>Health>Colors> custom backdrop it should be change the backdrop for the selected color.

### What actually happened?

Nothing happens, the backdrop color, continues be the class color.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/Merathilis/ElvUI_MerathilisUI/blob/development/CHANGELOG.md) and done the [Troubleshooting Steps](https://github.com/Merathilis/ElvUI_MerathilisUI/wiki/Troubleshooting).
- [X] I have disabled all addons except the AddOns called 'ElvUI' and 'ElvUI OptionsUI' and 'ElvUI_MerathilisUI' by using `/muidebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and/or MerathilisUI and another addon, make sure you include that information.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I gave you information above on which XPack i play Classic, WotLK or Retail.

**Comment by Merathilis** [comment]
That's not a bug. Since you use my Gradient Mode it will get overwritten.
