### ISSUE TITLE
[Bug Report] LUA error for BagSync addon

### ISSUE THREAD

**Issue by Calen81** [Merathilis/ElvUI_MerathilisUI#88]
### What is the issue you are having?

After resent update for Retail, I keep getting a LUA error for the Addon >BagSync<.
I don't have that installed xD

### What is the expected behavior?

No error

### What actually happened?

As above

### Errors

```shell
1x .../ElvUI_MerathilisUI/Modules/Skins/Extern/BagSync.lua:6: Usage: GetAddon(name): 'name' - Cannot find an AceAddon 'BagSync'.
[string "=[C]"]: ?
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:151: in function `GetAddon'
[string "@ElvUI_MerathilisUI/Modules/Skins/Extern/BagSync.lua"]:6: in main chunk

Locals:
(*temporary) = "Usage: GetAddon(name): 'name' - Cannot find an AceAddon 'BagSync'."
```

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/Merathilis/ElvUI_MerathilisUI/blob/development/CHANGELOG.md) and done the [Troubleshooting Steps](https://github.com/Merathilis/ElvUI_MerathilisUI/wiki/Troubleshooting).
- [X] I have disabled all addons except the AddOns called 'ElvUI' and 'ElvUI OptionsUI' and 'ElvUI_MerathilisUI' by using `/muidebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and/or MerathilisUI and another addon, make sure you include that information.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I gave you information above on which XPack i play Classic, WotLK or Retail.

**Comment by Merathilis** [comment]
Will be fixed with the next version. Thx
