### ISSUE TITLE
 [Bug Report] Chat not working

### ISSUE THREAD

**Issue by angellic01** [Merathilis/ElvUI_MerathilisUI#89]
### What is the issue you are having?

System messages, guild chat, general chat, ALL chat is not showing up at all.  I can't see system messages either, such as /rolls.

### What is the expected behavior?

I expect to be able to see chat.

### What actually happened?

System messages, guild chat, general chat, ALL chat is not showing up at all.  I can't see system messages either, such as /rolls.
I am playing SOD Classic. (and is there ANYTHING I can do to get you to keep supporting this version, PLEASE)

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/Merathilis/ElvUI_MerathilisUI/blob/development/CHANGELOG.md) and done the [Troubleshooting Steps](https://github.com/Merathilis/ElvUI_MerathilisUI/wiki/Troubleshooting).
- [X] I have disabled all addons except the AddOns called 'ElvUI' and 'ElvUI OptionsUI' and 'ElvUI_MerathilisUI' by using `/muidebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and/or MerathilisUI and another addon, make sure you include that information.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I gave you information above on which XPack i play Classic, WotLK or Retail.

**Comment by 1Botanica1** [comment]
MerathalisUI isn’t for classic, only retail.  It won’t work on Classic and there isn’t support for it on classic.

**Comment by Merathilis** [comment]
@1Botanica1 already mentioned. I don't support classic since a long time anymore.
