### ISSUE TITLE
[Bug Report] <Custom Text Error & RCLootcouncil Error>

### ISSUE THREAD

**Issue by Hamsta101** [Merathilis/ElvUI_MerathilisUI#90]
![Untitled 2](https://github.com/Merathilis/ElvUI_MerathilisUI/assets/168144479/bb6b30e3-213d-4387-b211-4a2da4b7cd89)
![Untitled](https://github.com/Merathilis/ElvUI_MerathilisUI/assets/168144479/1b293bcb-ba74-4323-a2bb-8ba4c9f9f53a)
### What is the issue you are having?

Since update on April 13th 2024 (6.10) - 
(1) Custom Text formulas stopped working for Nameplates:

(2) RCLootCouncil clashing with Merathilis UI:

Recent update on April 25th 2024 (6.11) - did not change any of these issues

### What is the expected behavior?

(1) Nameplate Custom Text:
*Plates should be displayed (remaining health, name - instead of showing the formula

(2) RCLootCouncil:
*there should be no UI conflicts?

### What actually happened?

Since update on April 13th 2024 (6.10) - 
(1) Custom Text formulas stopped working for Nameplates:
_*Player Nameplate
*Target Nameplate
*Boss Frames
*possibly other frames?_

(2) RCLootCouncil clashing with Merathilis UI:
_*UI Error (yellow text) every 10-15 seconds
*If RCLootCouncil is active, autobuttons and actionbars disregard 'mouseover' and 'global fade' checked boxes - and no longer show (even when mouseovered - but tooltip shows?)_

Recent update on April 25th 2024 (6.11) - did not change any of these issues

### Suggested Solution/Workaround

No idea regarding the custom texts - currently have RCLootCouncil de-activated to avoid UI errors

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/Merathilis/ElvUI_MerathilisUI/blob/development/CHANGELOG.md) and done the [Troubleshooting Steps](https://github.com/Merathilis/ElvUI_MerathilisUI/wiki/Troubleshooting).
- [X] I have disabled all addons except the AddOns called 'ElvUI' and 'ElvUI OptionsUI' and 'ElvUI_MerathilisUI' by using `/muidebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and/or MerathilisUI and another addon, make sure you include that information.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I gave you information above on which XPack i play Classic, WotLK or Retail.

**Comment by Merathilis** [comment]
1) Is Unitframes not Nameplates. And it was mentioned in the changelog that i removed some old tags. Which means, you now have to change them manually if you dont want to use your settings or run the Installer from me again and do only the step from the UnitFrames again.

2) Cant confirm your issue.

Also, please do not use my Ticket Tracker for simple Questions, i have a Discord server, please join there. And my latest Version is 6.12 not 6.11
