### ISSUE TITLE
[Bug Report] <Raid Buff Reminder>

### ISSUE THREAD

**Issue by ecrasy** [Merathilis/ElvUI_MerathilisUI#92]
### What is the issue you are having?

1x ...ElvUI_MerathilisUI/Modules/RBReminder/RBReminder.lua:365: attempt to index field 'Anchor' (a nil value)
[string "@ElvUI_MerathilisUI/Modules/RBReminder/RBReminder.lua"]:365: in function `Visibility'
[string "@ElvUI_MerathilisUI/Options/Modules/RBReminders.lua"]:33: in function <...s/ElvUI_MerathilisUI/Options/Modules/RBReminders.lua:31>

### What is the expected behavior?

RBReminder function well

### What actually happened?

RBReminder bug with nil value reference

### Suggested Solution/Workaround

Thanks for the work

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/Merathilis/ElvUI_MerathilisUI/blob/development/CHANGELOG.md) and done the [Troubleshooting Steps](https://github.com/Merathilis/ElvUI_MerathilisUI/wiki/Troubleshooting).
- [X] I have disabled all addons except the AddOns called 'ElvUI' and 'ElvUI OptionsUI' and 'ElvUI_MerathilisUI' by using `/muidebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and/or MerathilisUI and another addon, make sure you include that information.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I gave you information above on which XPack i play Classic, WotLK or Retail.

**Comment by Merathilis** [comment]
Without giving me any useful infos (ElvUI Version? MerathilisUI Version?), and a way to reproduce the error, i will immediately close this.

Feel free to reopen this if you updated this ticket.

**Comment by ecrasy** [comment]
I have updated the issue.
How can it be reopen?

**Comment by Merathilis** [comment]
![image](https://github.com/user-attachments/assets/00681532-3368-48a8-bfd7-5ff8ed051753)


But before you reopen it, please manually delete my ElvUI_MerathilisUI folder from your AddOn folder and download a fresh copy
