### ISSUE TITLE
[Feature Request] Mail Module toggle Withdraw Gold button on/off

### ISSUE THREAD

**Issue by AngelosNaoumis** [Merathilis/ElvUI_MerathilisUI#97]
**Is your feature request related to a problem? Please describe.**
Not a problem, it just breaks my skinning :D

**Describe the solution you'd like**
A toggle to turn off withdraw gold button when you enable mail module.

**Describe alternatives you've considered**
Turning off the module, but I like the feature of alts

**Comment by Merathilis** [comment]
I'm sorry, what do i break with the Mail Module?

![image](https://github.com/user-attachments/assets/0ba0de69-5c06-4b9a-9d5f-53933f6f8313)
