### ISSUE TITLE
Wormhole for TWW added to top bar

### ISSUE THREAD

**Issue by GumseGuZz** [Merathilis/ElvUI_MerathilisUI#98]
Wormhole for TWW added to top bar :D

**Comment by Merathilis** [comment]
Please hijack my ticket tracker for this. if you have simple questions, join my discord. and please use common english please.

**Comment by GumseGuZz** [comment]
BugTracker:
Report any **issue or suggestion** on the [Ticket Tracker](https://github.com/Merathilis/ElvUI_MerathilisUI/issues) by creating a Ticket

I'll try and communicate in "common English" You are missing the wormhole Generator: Khaz Algar in the top DataTexts called "MER_TopPanel"

I was trying to suggest you are missing that... i fail to see what i did wrong?... this is my first time doing this, but i dont think i will be doing it no more, you come of as a dick

**Comment by Merathilis** [comment]
First of all, the DataText is not from my AddOn. So mostly that you fail by not following the simple rules.
